### ISSUE TITLE
.NET Bio flashback

### ISSUE THREAD

**Issue by filicado** [dotnetbio/bio#21]
I have to revisit an old .NET bio project from a few years back. However, in the meantime I have left the Windows world behind. So I installed MonoDevelop (on Ubuntu 16.04) to see if it would work. I was trying to migrate the old code but it gives problems with simple things that worked fine. For example this:
      
		Sequence tsequence = new Sequence(Bio.Alphabets.RNA, line1.ToString());
      
Now throws an exceptions saying "The type initializer for 'Bio.Alphabets' threw an exception."
Apparently I need to "add a reference to a Bio.Platform.Helpers library."
Any ideas?

**Comment by markjulmar** [comment]
Just use the published Nuget package. It adds all the pieces you need for
each platform.

On Tue, May 24, 2016 at 10:26 AM, filicado <notifications@github.com> wrote:

> I have to revisit an old .NET bio project from a few years back. However,
> in the meantime I have left the Windows world behind. So I installed
> MonoDevelop (on Ubuntu 16.04) to see if it would work. I was trying to
> migrate the old code but it gives problems with simple things that worked
> fine. For example this:
>
>     Sequence tsequence = new Sequence(Bio.Alphabets.RNA, line1.ToString());
>
> Now throws an exceptions saying "The type initializer for 'Bio.Alphabets'
> threw an exception."
> Apparently I need to "add a reference to a Bio.Platform.Helpers library."
> Any ideas?
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/dotnetbio/bio/issues/21>
>



-- 

Mark Smith

mark@julmar.com | @marksm <http://www.twitter.com/marksm> | 214-774-4749 |
www.julmar.com

**Comment by filicado** [comment]
This was actually my first attempt but that gave me: "Unable to resolve dependency 'NetBioCore.PCL (≥ 2.0.150722)'."

**Comment by markjulmar** [comment]
Hmm.. that's weird. I wonder if MonoDevelop has issues with NuGet. The
package is here: https://www.nuget.org/packages/NETBioCore.PCL/

I know Xamarin Studio (the Mac version of MonoDevelop) doesn't have any
trouble. I'll ask Matt Ward who developed the plug in for the IDE.

But you can solve it easily enough by adding a reference (from source) to
the proper platform-specific assembly. You want the full desktop variant.
Or, check with Nigel, he's got a solution that combines it all into one DLL
I think.

mark

On Tue, May 24, 2016 at 10:45 AM, filicado <notifications@github.com> wrote:

> This was actually my first attempt but that gave me: "Unable to resolve
> dependency 'NetBioCore.PCL (≥ 2.0.150722)'."
>
> —
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub
> <https://github.com/dotnetbio/bio/issues/21#issuecomment-221314033>
>



-- 

Mark Smith

mark@julmar.com | @marksm <http://www.twitter.com/marksm> | 214-774-4749 |
www.julmar.com

**Comment by filicado** [comment]
That did the trick thanks, now only ~300 other issues to take care of

**Comment by evolvedmicrobe** [comment]
Dare I ask what the remaining 300 are? I run the library on Ubuntu all the time so have probably encountered some of them.

**Comment by filicado** [comment]
Sorry, nothing related to .NET bio I'm using it for pretty pedestrians stuff. It's just a small tool that generates TALEN coding sequences and makes sure that RVDs match each other as little as possible.
Actually after I set the target to Mono 4.5 linq code also worked suddenly and it all ran (slow) fine!

**Comment by ambi1999** [comment]
HI Filicado,

How did you manage to solve this issue. I got similar message (on visual studio community 2015) recently and have not been able to resolve it.

Cheers,
Ambi.
