### ISSUE TITLE
The type initializer for 'Bio.Alphabets' threw an exception

### ISSUE THREAD

**Issue by ambi1999** [dotnetbio/bio#22]
Hi,

I am getting following error even in basic code using dotnetbio on windows and visual stduio 2015 community edition.

Code: // Create two sequences; normally you'd have this already.
            ISequence dna1 = new Sequence(Alphabets.AmbiguousDNA, "ACTGAAGGATATTA");

Error message
The type initializer for 'Bio.Alphabets' threw an exception.

Thx for your help,
Ambi.

**Comment by evolvedmicrobe** [comment]
Hi Ambi,

Do you have a longer stack trace for this message? It's hard to tell what's going on from just this, though it may be related to some missing PCL libraries.

Cheers,
Nigel

**Comment by evolvedmicrobe** [comment]
Am closing this issue.  I also just committed a change that moves away from the PCLs in preparation of the upcoming .NET Core transition.
