### ISSUE TITLE
where is connection information

### ISSUE THREAD

**Issue by TayyabaQamar** [dotnetbio/bio#27]
I want to build this project in Visual studio that's why i need the server information for .Net Bio project.

**Comment by markjulmar** [comment]
Not sure what you mean - there's no server project. If you are referring to a source control system - it was originally linked to a Codeplex project, but it's not anymore - now it's here on Github.

**Comment by TayyabaQamar** [comment]
ok.. So what exactly i should have to do is to build the solution in Visual Studio?. Is there any library or something (prerequisites) that should be imported before building the solution?. I read the Documentation in codeplex site of .Net Bio project, it was mentioned there that you should add and connect to a server before building the project. I tried to build the solution downloaded from codeplex site but it was giving me errors.

**Comment by TayyabaQamar** [comment]
I actually downloaded the source code and i want to build it in Visual studio but facing errors. I am a Bioinformatician and working on my project in which i have to create an online Database (Website) and where people can do the blast with my database and other functionalities. I wanted to copy the code of Blast from this .Net Bio Project and use it in y project.

**Comment by evolvedmicrobe** [comment]
Am closing this as I am also not sure what they mean.
