### ISSUE TITLE
Bio.Platform.Helpers.PlatformServices causes exceptions to be thrown on fresh build

### ISSUE THREAD

**Issue by evolvedmicrobe** [dotnetbio/bio#4]
If you build and copy Bio.Desktop, you can't parse a FASTA File because 

Bio.Platform.Helpers.PlatformServices.MaxSequenceSize is set to 0.  This leads to a very confusing "sequence is longer than 2GB error when this line of code executes in the FASTA parser.

    if ((((long)bufferPosition + line.Length) >= PlatformManager.Services.MaxSequenceSize))
    {
        throw new ArgumentOutOfRangeException(
            string.Format(CultureInfo.CurrentUICulture, Properties.Resource.SequenceDataGreaterthan2GB, name));
    }

Presumably this is set somehow by nuget or other deployment mechanisms?  Do we know how we can make it work for the general build case?

**Comment by markjulmar** [comment]
There are two DLLs which must be included -- I'm thinking the wrong one is being set here, we might need to copy the `.csproj` file and make a file rename .. let me play with it.

**Comment by evolvedmicrobe** [comment]
I seem to be able to avoid the error if I copy out 

    src/Source/Framework/Shims/Bio.Platform.Helpers.Desktop/bin/Release/Bio.Platform.Helpers.*

into the build directory of Bio.Desktop

**Comment by evolvedmicrobe** [comment]
This should be fixed by the latest commit.
