### ISSUE TITLE
Issues with installing the BioTools

### ISSUE THREAD

**Issue by residentx10** [dotnetbio/bio#6]
I used the tools before they became a part of OuterCurve. Now you've move them to GitHub. 
I tried to compile the libraries to build the tools but I get this error. What type of project do I need to create for nuget to install correctly?

I'm trying to install the .NET BIO libraries,  https://github.com/dotnetbio/bio , from Nuget but when I enter the correct commands into the package console I get this error:

PM> Install-Package NETBioCore.PCL

Install-Package : The current environment doesn't have a solution open.

At line:1 char:1

+ Install-Package NETBioCore.PCL

+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

    + CategoryInfo          : InvalidOperation: (:) [Install-Package], Invalid 

   OperationException

    + FullyQualifiedErrorId : NuGetNoActiveSolution,NuGet.PackageManagement.Po 

   werShellCmdlets.InstallPackageCommand

**Comment by markjulmar** [comment]
Hi George,

The Nuget approach is if you want to use the _libraries_ for your own C# code. This doesn't include the command-line tools, those were just samples built around the libraries.

If you want the command-line tools, then download this: http://bio.codeplex.com/downloads/get/677214

That is a standalone MSI installer which includes the binary tools and will create the .NET Bio folder for you.

I hope that helps!
